{% macro us_state_to_iso_3166_2(state_col, default_value="'UNKNOWN'") %}
    case upper(trim({{ state_col }}))
        when 'ALABAMA' then 'US-AL'
        when 'ALASKA' then 'US-AK'
        when 'ARIZONA' then 'US-AZ'
        when 'ARKANSAS' then 'US-AR'
        when 'CALIFORNIA' then 'US-CA'
        when 'COLORADO' then 'US-CO'
        when 'CONNECTICUT' then 'US-CT'
        when 'DELAWARE' then 'US-DE'
        when 'FLORIDA' then 'US-FL'
        when 'GEORGIA' then 'US-GA'
        when 'HAWAII' then 'US-HI'
        when 'IDAHO' then 'US-ID'
        when 'ILLINOIS' then 'US-IL'
        when 'INDIANA' then 'US-IN'
        when 'IOWA' then 'US-IA'
        when 'KANSAS' then 'US-KS'
        when 'KENTUCKY' then 'US-KY'
        when 'LOUISIANA' then 'US-LA'
        when 'MAINE' then 'US-ME'
        when 'MARYLAND' then 'US-MD'
        when 'MASSACHUSETTS' then 'US-MA'
        when 'MICHIGAN' then 'US-MI'
        when 'MINNESOTA' then 'US-MN'
        when 'MISSISSIPPI' then 'US-MS'
        when 'MISSOURI' then 'US-MO'
        when 'MONTANA' then 'US-MT'
        when 'NEBRASKA' then 'US-NE'
        when 'NEVADA' then 'US-NV'
        when 'NEW HAMPSHIRE' then 'US-NH'
        when 'NEW JERSEY' then 'US-NJ'
        when 'NEW MEXICO' then 'US-NM'
        when 'NEW YORK' then 'US-NY'
        when 'NORTH CAROLINA' then 'US-NC'
        when 'NORTH DAKOTA' then 'US-ND'
        when 'OHIO' then 'US-OH'
        when 'OKLAHOMA' then 'US-OK'
        when 'OREGON' then 'US-OR'
        when 'PENNSYLVANIA' then 'US-PA'
        when 'RHODE ISLAND' then 'US-RI'
        when 'SOUTH CAROLINA' then 'US-SC'
        when 'SOUTH DAKOTA' then 'US-SD'
        when 'TENNESSEE' then 'US-TN'
        when 'TEXAS' then 'US-TX'
        when 'UTAH' then 'US-UT'
        when 'VERMONT' then 'US-VT'
        when 'VIRGINIA' then 'US-VA'
        when 'WASHINGTON' then 'US-WA'
        when 'WEST VIRGINIA' then 'US-WV'
        when 'WISCONSIN' then 'US-WI'
        when 'WYOMING' then 'US-WY'
        else {{ default_value }}
    end
{% endmacro %}
