version: 2

sources:
  - name: bike_business
    database: business_operations
    schema: raw
    tables:
      - name: fx_latest_rate
        loaded_at_field: _airbyte_extracted_at
        freshness:
          warn_after: {count: 2, period: hour}
      - name: sentiment      
        loaded_at_field: _airbyte_extracted_at
        freshness:
          warn_after: {count: 2, period: hour}
      - name: ops_address
      - name: ops_country_region
      - name: ops_credit_card
      - name: ops_customer
      - name: ops_person
      - name: ops_product_category
      - name: ops_product_history
      - name: ops_product_subcategory
      - name: ops_salesorderdetail
      - name: ops_salesorderheader
      - name: ops_salesreason
      - name: ops_stateprovince
      - name: ops_store
      - name: ops_workorder
